# Generated by Django 3.2.9 on 2021-11-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corePoker', '0002_player_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='positionInDeck',
            field=models.IntegerField(null=True),
        ),
    ]
