# Generated by Django 3.2.9 on 2021-11-29 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corePoker', '0004_alter_deck_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corePoker.game'),
        ),
    ]
