# Generated by Django 3.2.9 on 2021-12-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corePoker', '0006_alter_player_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jugada',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='numMasAlto',
            field=models.IntegerField(null=True),
        ),
    ]
