# Generated by Django 3.2.9 on 2021-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corePoker', '0010_game_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aCambiado',
            field=models.BooleanField(default=False),
        ),
    ]
