# Generated by Django 3.2.9 on 2021-12-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corePoker', '0013_auto_20211210_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='implicadaEnJugada',
            field=models.BooleanField(default=False),
        ),
    ]
