# Generated by Django 3.2.9 on 2022-01-19 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corePoker', '0014_card_implicadaenjugada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand', to='corePoker.player'),
        ),
    ]
